//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitarbeiterverwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitarbeiter
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string GKlasse { get; set; }
        public string Kontonummer { get; set; }
        public Nullable<bool> UeBest { get; set; }
        public Nullable<int> Verdienst { get; set; }
        public string Passwort { get; set; }
        public string Benutzername { get; set; }
    }
}
